---
- name: Run Jenkins container
  hosts: localhost
  become: true

  tasks:
    - name: Pull Jenkins image
      docker_image:
        name: jenkins/jenkins
        state: present

    - name: Start Jenkins container
      docker_container:
        name: my_jenkins
        image: jenkins/jenkins
        ports:
          - "80:8080"
        volumes:
          - ./jenkins_home:/var/jenkins_home
        restart_policy: always

